spring:
  application:
    name: zuul-service

server:
  port: 9000

#zuul:
#  routes:
#    blog:
#      path: /ymq/**
#      url: http://www.ymq.io/about

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api:
      path: /**
      serviceId: eureka-provider
